import lviv from '../../../../data/maps/lviv.json'
import minsk from '../../../../data/maps/minsk.json'
import moscow from '../../../../data/maps/moscow.json'
import smolensk from '../../../../data/maps/smolensk.json'
import volhynia from '../../../../data/maps/volhynia.json'
import vyazma from '../../../../data/maps/vyazma.json'
import { registerMap } from '../map'
import type { MapData } from '../map'
import type { Campaign } from '../missions'
import { arm, inf, rec } from './oob'

for (const map of [lviv, volhynia, minsk, smolensk, vyazma, moscow]) registerMap(map as unknown as MapData)

export const EAST_1941: Campaign = {
  id: 'east1941',
  name: 'East 1941',
  side: 'Soviet Union',
  blurb: 'From the frontier to the gates of Moscow — and back.',
  missions: [
    {
      id: 'border@2',
      name: 'The Frontier',
      date: 'June 1941',
      briefing:
        'The panzers have crossed the Bug at Sokal and are driving for Brody and Dubno. Behind ' +
        'them your frontier armies still stand on the San and around Rava-Ruska, in a salient ' +
        'the enemy means to cut off at its root. Get the frontier corps out east while the line ' +
        'still has a way home — every corps that ends the battle with a route to the rear is an ' +
        'army you will have in July. Lviv is worth holding only if it does not cost them.',
      mapId: 'lviv',
      sides: ['Germany', 'Soviet Union'],
      held: [
        'przeworsk', 'lezajsk', 'jaroslaw', 'radymno', 'dynow', 'bircza', 'sanok', 'lubaczow', 'bilgoraj', 'narol',
        'tomaszow', 'zamosc', 'tyszowce', 'hrubieszow', 'dolhobyczow', 'sokal', 'velykimosty', 'volodymyr',
      ],
      home: [['jaroslaw', 'zamosc', 'przeworsk', 'bilgoraj'], ['kremenets', 'shumsk', 'zbarazh', 'terebovlia']],
      formations: [
        arm(0, 'sokal'),
        arm(0, 'sokal'),
        rec(0, 'velykimosty'),
        arm(0, 'dolhobyczow'),
        inf(0, 'hrubieszow'),
        inf(0, 'hrubieszow'),
        arm(0, 'volodymyr'),
        inf(0, 'volodymyr'),
        inf(0, 'dolhobyczow'),
        inf(0, 'narol'),
        inf(0, 'tomaszow'),
        inf(0, 'tomaszow'),
        inf(0, 'lubaczow'),
        inf(0, 'lubaczow'),
        inf(0, 'jaroslaw'),
        inf(0, 'jaroslaw'),

        inf(1, 'przemysl', 2),
        inf(1, 'mostyska', 2),
        inf(1, 'yavoriv', 2),
        inf(1, 'ravaruska', 2),
        inf(1, 'zhovkva', 2),
        inf(1, 'ivanychi', 2),
        inf(1, 'lokachi', 2),
        inf(1, 'sambir', 2),
        inf(1, 'horokhiv', 2),
        arm(1, 'lviv'),
        arm(1, 'radekhiv'),
        arm(1, 'brody'),
        inf(1, 'lutsk', 2),
        inf(1, 'dubno', 2),
        rec(1, 'kamianka'),
      ],
      aims: ['lviv', 'brody', 'dubno', 'ternopil'],
      turns: 8,
      arrivals: [
        { turn: 2, side: 0, type: 'infantry', at: 'radymno' },
        { turn: 2, side: 0, type: 'armour', at: 'sokal' },
        { turn: 3, side: 0, type: 'armour', at: 'dolhobyczow' },
        { turn: 4, side: 0, type: 'infantry' },
        { turn: 5, side: 0, type: 'recon' },
        { turn: 3, side: 1, type: 'infantry' },
      ],
      save: { pocket: [16, 17, 18, 19, 20, 21, 22, 23], stars: [6, 7, 8] },
      player: 1,
      enemy: 'maneuver',
    },
    {
      id: 'dubno@1',
      name: 'Dubno',
      date: 'June 1941',
      briefing:
        'Kleist\'s panzers have driven a wedge from Sokal through Lutsk to Dubno, and it is still ' +
        'going east for Rivne and Ostroh. Its flanks are long and thinly held. Four mechanised ' +
        'corps are coming up — two from Brody in the south, two through Klevan and Kostopil in the ' +
        'north — to strike the wedge from both sides. Hold Rivne and Brody until they arrive, then ' +
        'retake Dubno, Lutsk and Berestechko: whoever holds more of the five when it ends has won.',
      mapId: 'volhynia',
      sides: ['Germany', 'Soviet Union'],
      held: [
        'lublin', 'chelm', 'wlodawa', 'zamosc', 'hrubieszow', 'tomaszow', 'jaroslaw', 'lubaczow', 'bilgoraj',
        'ravaruska', 'sokal', 'volodymyr', 'lyuboml', 'lokachi', 'horokhiv', 'radekhiv', 'berestechko', 'lutsk',
        'kivertsi', 'mlyniv', 'dubno', 'zhovkva', 'kamianka',
      ],
      home: [['lublin', 'zamosc', 'chelm', 'hrubieszow'], ['zhytomyr', 'berdychiv', 'proskuriv', 'korosten', 'novohrad']],
      formations: [
        arm(0, 'dubno'),
        arm(0, 'dubno'),
        inf(0, 'dubno'),
        arm(0, 'mlyniv'),
        arm(0, 'mlyniv'),
        rec(0, 'mlyniv'),
        arm(0, 'lutsk'),
        inf(0, 'lutsk'),
        inf(0, 'kivertsi'),
        inf(0, 'berestechko'),
        inf(0, 'berestechko'),
        inf(0, 'radekhiv'),
        inf(0, 'horokhiv'),
        inf(0, 'lokachi'),
        inf(0, 'ravaruska'),
        inf(0, 'lyuboml'),
        inf(0, 'sokal'),
        inf(0, 'zhovkva'),
        inf(0, 'kamianka'),

        inf(1, 'rivne', 2),
        inf(1, 'klevan', 2),
        inf(1, 'tsuman', 2),
        inf(1, 'ostroh', 2),
        inf(1, 'brody', 2),
        inf(1, 'lviv', 2),
        inf(1, 'zolochiv', 2),
        arm(1, 'zolochiv'),
        rec(1, 'shumsk'),
      ],
      aims: ['dubno', 'lutsk', 'berestechko', 'rivne', 'brody'],
      turns: 8,
      arrivals: [
        { turn: 2, side: 1, type: 'armour', at: 'brody' },
        { turn: 3, side: 1, type: 'armour', at: 'kostopil' },
        { turn: 4, side: 1, type: 'armour', at: 'zbarazh' },
        { turn: 5, side: 1, type: 'armour', at: 'kostopil' },
        { turn: 2, side: 0, type: 'infantry' },
        { turn: 3, side: 0, type: 'armour' },
        { turn: 4, side: 0, type: 'infantry' },
        { turn: 5, side: 0, type: 'infantry' },
      ],
      player: 1,
      enemy: 'maneuver',
    },
    {
      id: 'minsk@1',
      name: 'Minsk',
      date: 'July 1941',
      briefing:
        'The panzer groups have met at Minsk, and the Western Front\'s armies are in the forests ' +
        'between Navahrudak and Stowbtsy with the enemy on every side. The German infantry is ' +
        'marching up to fill the ring. Break out east — through Dzyarzhynsk and Uzda, or past Minsk — ' +
        'to the line forming on the Berezina, which will attack to meet you. The corps that end the ' +
        'battle with a route home are all that counts; the rest is ground.',
      mapId: 'minsk',
      sides: ['Germany', 'Soviet Union'],
      held: [
        'suwalki', 'augustow', 'bialystok', 'bielsk', 'hajnowka', 'sokolka', 'grodno', 'druskininkai', 'brest', 'kobryn',
        'pruzhany', 'bialowieza', 'svislach', 'vawkavysk', 'masty', 'shchuchyn', 'zelva', 'slonim', 'byaroza',
        'ivatsevichy', 'drahichyn', 'pinsk', 'luninets', 'hantsavichy', 'lida', 'radun', 'varena', 'vilnius',
        'eisiskes', 'ashmyany', 'baranovichi', 'lyakhavichy', 'kletsk', 'nesvizh', 'smarhon', 'maladzyechna',
        'vileyka', 'dzyarzhynsk', 'radashkovichy', 'minsk', 'lahoysk', 'uzda', 'kapyl', 'slutsk', 'rudzensk',
      ],
      home: [['bialystok', 'grodno', 'brest', 'vilnius', 'suwalki'], ['babruysk', 'barysaw', 'krupki', 'lepel', 'berazino']],
      formations: [
        arm(0, 'minsk'),
        arm(0, 'minsk'),
        inf(0, 'minsk'),
        arm(0, 'radashkovichy'),
        inf(0, 'maladzyechna'),
        inf(0, 'ashmyany'),
        arm(0, 'dzyarzhynsk'),
        inf(0, 'dzyarzhynsk'),
        inf(0, 'uzda'),
        inf(0, 'nesvizh'),
        inf(0, 'baranovichi'),
        arm(0, 'slutsk'),
        inf(0, 'slutsk'),
        inf(0, 'shchuchyn'),
        inf(0, 'radun'),
        inf(0, 'slonim'),
        inf(0, 'lida'),
        inf(0, 'eisiskes'),

        inf(1, 'navahrudak', 2),
        inf(1, 'navahrudak', 2),
        inf(1, 'ivye', 2),
        inf(1, 'dzyatlava', 2),
        inf(1, 'mir', 2),
        inf(1, 'stowbtsy', 2),
        inf(1, 'valozhyn', 2),
        inf(1, 'rakaw', 2),
        { side: 1, type: 'armour', at: 'stowbtsy', strength: 2 },
        { side: 1, type: 'armour', at: 'mir', strength: 2 },
        rec(1, 'valozhyn'),
        { ...inf(1, 'smilavichy', 2), fresh: true },
        { ...inf(1, 'marinahorka', 2), fresh: true },
        { ...inf(1, 'chervyen', 2), fresh: true },
        { ...inf(1, 'barysaw', 2), fresh: true },
        { ...arm(1, 'chervyen'), fresh: true },
      ],
      aims: ['minsk', 'dzyarzhynsk', 'uzda', 'smilavichy', 'stowbtsy'],
      turns: 8,
      arrivals: [
        { turn: 2, side: 0, type: 'armour' },
        { turn: 3, side: 0, type: 'infantry' },
        { turn: 4, side: 0, type: 'infantry' },
        { turn: 3, side: 1, type: 'infantry' },
        { turn: 5, side: 1, type: 'armour' },
      ],
      save: { pocket: [18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28], stars: [5, 6, 7] },
      player: 1,
      enemy: 'depth',
    },
    {
      id: 'smolensk@1',
      name: 'Smolensk',
      date: 'July 1941',
      briefing:
        'Two of your armies hold Smolensk and the forests north of it, and the panzers have closed ' +
        'behind them at Yartsevo and on the Dnieper crossing at Solovyovo. They can hold out on what ' +
        'they carry for a few days, not a week. Strike west from Dorogobuzh, Bely and Roslavl and ' +
        'open a road back to them — every pocket corps with a route home at the end is saved, and ' +
        'any that are not are lost with the city.',
      mapId: 'smolensk',
      sides: ['Germany', 'Soviet Union'],
      held: [
        'vitebsk', 'gorodok', 'surazh', 'liozna', 'orsha', 'dubrovna', 'shklov', 'mogilev', 'horki', 'mstsislaw',
        'krichev', 'bykhaw', 'chavusy', 'velizh', 'nevel', 'demidov', 'lyubavichi', 'krasny', 'monastyrshchina',
        'khislavichi', 'pochinok', 'yelnya', 'glinka', 'dukhovshchina', 'yartsevo', 'solovyovo', 'prechistoye',
      ],
      home: [['vitebsk', 'orsha', 'mogilev'], ['vyazma', 'sychevka', 'gzhatsk', 'yukhnov', 'kirov']],
      formations: [
        arm(0, 'yartsevo'),
        inf(0, 'yartsevo'),
        inf(0, 'solovyovo'),
        arm(0, 'dukhovshchina'),
        inf(0, 'dukhovshchina'),
        inf(0, 'demidov'),
        inf(0, 'prechistoye'),
        inf(0, 'liozna'),
        inf(0, 'lyubavichi'),
        inf(0, 'krasny'),
        inf(0, 'monastyrshchina'),
        arm(0, 'pochinok'),
        inf(0, 'pochinok'),
        arm(0, 'yelnya'),
        inf(0, 'yelnya'),
        inf(0, 'glinka'),

        inf(1, 'smolensk', 2),
        inf(1, 'smolensk', 2),
        inf(1, 'smolensk', 2),
        inf(1, 'katyn', 2),
        inf(1, 'katyn', 2),
        inf(1, 'kasplya', 2),
        inf(1, 'kasplya', 2),
        inf(1, 'rudnya', 2),
        { side: 1, type: 'armour', at: 'rudnya', strength: 2 },
        arm(1, 'dorogobuzh'),
        rec(1, 'safonovo'),
        { ...inf(1, 'dorogobuzh', 2), fresh: true },
        { ...inf(1, 'safonovo', 2), fresh: true },
        { ...inf(1, 'kholm', 2), fresh: true },
        { ...inf(1, 'bely', 2), fresh: true },
        { ...inf(1, 'roslavl', 2), fresh: true },
        { ...arm(1, 'roslavl'), fresh: true },
        { ...inf(1, 'spasdemensk', 2), fresh: true },
      ],
      aims: ['smolensk', 'yartsevo', 'solovyovo', 'pochinok', 'yelnya'],
      turns: 8,
      arrivals: [
        { turn: 2, side: 0, type: 'armour' },
        { turn: 3, side: 0, type: 'infantry' },
        { turn: 2, side: 1, type: 'infantry' },
        { turn: 3, side: 1, type: 'infantry' },
        { turn: 4, side: 1, type: 'armour' },
      ],
      save: { pocket: [16, 17, 18, 19, 20, 21, 22, 23, 24], stars: [6, 7, 8] },
      player: 1,
      enemy: 'depth',
    },
    {
      id: 'kievpocket@1',
      name: 'Kiev Pocket',
      date: 'September 1941',
      briefing:
        'Guderian and Kleist have met at Lokhvytsia, and the whole Southwestern Front is inside ' +
        'the ring — Kyiv, the Dnieper line and everything east of it to Pryluky. Stavka has at last ' +
        'allowed you to go. Break east through Lokhvytsia or Romny to the line at Hadiach and ' +
        'Lebedyn, which will attack to meet you. Only the corps that end the battle with a route ' +
        'home count; Kyiv is worth holding only while it costs the enemy more than it costs you.',
      mapId: 'kiev',
      sides: ['Germany', 'Soviet Union'],
      held: [
        'gomel', 'mozyr', 'starodub', 'horodnia', 'novhorod', 'shostka', 'hlukhiv', 'putyvl', 'chernihiv', 'mena',
        'korop', 'konotop', 'bakhmach', 'romny', 'lokhvytsia', 'lubny', 'myrhorod', 'khorol', 'semenivka',
        'kobeliaky', 'kremenchuk', 'chyhyryn', 'oleksandriia', 'kirovohrad', 'novomyrhorod', 'zvenyhorodka',
        'uman', 'korsun', 'vinnytsia', 'bilatserkva', 'berdychiv', 'fastiv', 'zhytomyr', 'malyn', 'ovruch',
        'irpin', 'chernobyl',
      ],
      home: [['gomel', 'starodub', 'zhytomyr', 'vinnytsia', 'kirovohrad'], ['sumy', 'lebedyn', 'okhtyrka', 'karlivka', 'poltava']],
      formations: [
        arm(0, 'romny'),
        arm(0, 'romny'),
        inf(0, 'romny'),
        arm(0, 'lokhvytsia'),
        arm(0, 'lokhvytsia'),
        inf(0, 'lokhvytsia'),
        arm(0, 'lubny'),
        inf(0, 'lubny'),
        arm(0, 'myrhorod'),
        inf(0, 'myrhorod'),
        inf(0, 'khorol'),
        inf(0, 'semenivka'),
        inf(0, 'konotop'),
        inf(0, 'bakhmach'),
        inf(0, 'mena'),
        inf(0, 'chernihiv'),
        inf(0, 'chernobyl'),
        inf(0, 'irpin'),
        inf(0, 'fastiv'),
        inf(0, 'bilatserkva'),
        inf(0, 'korsun'),

        inf(1, 'pryluky', 2),
        inf(1, 'pryluky', 2),
        inf(1, 'pyriatyn', 2),
        inf(1, 'ichnia', 2),
        inf(1, 'nizhyn', 2),
        inf(1, 'yahotyn', 2),
        inf(1, 'zolotonosha', 2),
        inf(1, 'kozelets', 2),
        inf(1, 'boryspil', 2),
        inf(1, 'cherkasy', 2),
        { side: 1, type: 'armour', at: 'pryluky', strength: 2 },
        { side: 1, type: 'armour', at: 'yahotyn', strength: 2 },
        rec(1, 'pyriatyn'),
        { ...inf(1, 'kyiv', 2), fresh: true },
        { ...inf(1, 'kyiv', 2), fresh: true },
        { ...inf(1, 'kaniv', 2), fresh: true },
        { ...inf(1, 'hadiach', 2), fresh: true },
        { ...inf(1, 'poltava', 2), fresh: true },
        { ...arm(1, 'hadiach'), fresh: true },
        { ...rec(1, 'lebedyn'), fresh: true },
      ],
      aims: ['lokhvytsia', 'romny', 'lubny', 'pryluky', 'kyiv'],
      turns: 7,
      arrivals: [
        { turn: 2, side: 0, type: 'infantry' },
        { turn: 3, side: 0, type: 'infantry' },
        { turn: 3, side: 1, type: 'infantry' },
      ],
      save: { pocket: [21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36], stars: [8, 10, 12] },
      player: 1,
      enemy: 'depth',
    },
    {
      id: 'typhoon@2',
      name: 'Typhoon',
      date: 'October 1941',
      briefing:
        'The fronts before Moscow have been broken at Vyazma and Bryansk, and what is left of them ' +
        'is dying in the pockets. Three panzer groups are coming on again: from Rzhev for ' +
        'Volokolamsk, down the Mozhaisk road in the centre, and from Orel for Tula. You hold every ' +
        'objective and have almost nothing to hold them with. Keep Moscow and Tula and most of the ' +
        'Mozhaisk line — the Siberian divisions are coming by rail — and make the panzers pay for ' +
        'every town: destroy them where they outrun their fuel.',
      mapId: 'vyazma',
      sides: ['Germany', 'Soviet Union'],
      held: [
        'nelidovo', 'olenino', 'rzhev', 'zubtsov', 'bely', 'sychevka', 'kholmzhirkovsky', 'dukhovshchina', 'yartsevo',
        'smolensk', 'safonovo', 'dorogobuzh', 'vyazma', 'temkino', 'gzhatsk', 'yukhnov', 'ugra', 'yelnya', 'pochinok',
        'spasdemensk', 'mosalsk', 'sukhinichi', 'kirov', 'roslavl', 'kletnya', 'zhukovka', 'lyudinovo', 'dyatkovo',
        'zhizdra', 'bolkhov', 'karachev', 'bryansk', 'mglin', 'pochep', 'mtsensk', 'orel',
      ],
      home: [['smolensk', 'roslavl', 'bryansk', 'orel'], ['moscow', 'podolsk', 'serpukhov', 'klin']],
      formations: [
        arm(0, 'zubtsov'),
        arm(0, 'zubtsov'),
        arm(0, 'sychevka'),
        inf(0, 'rzhev'),
        inf(0, 'rzhev'),
        arm(0, 'rzhev'),
        arm(0, 'gzhatsk'),
        arm(0, 'gzhatsk'),
        inf(0, 'gzhatsk'),
        inf(0, 'vyazma'),
        arm(0, 'yukhnov'),
        inf(0, 'yukhnov'),
        inf(0, 'mosalsk'),
        arm(0, 'mosalsk'),
        inf(0, 'sukhinichi'),
        arm(0, 'mtsensk'),
        arm(0, 'mtsensk'),
        inf(0, 'mtsensk'),
        inf(0, 'bolkhov'),
        inf(0, 'kirov'),
        inf(0, 'orel'),

        inf(1, 'medyn', 1),
        inf(1, 'volokolamsk', 1),
        inf(1, 'mozhaisk', 1),
        inf(1, 'maloyaroslavets', 1),
        inf(1, 'kaluga', 1),
        inf(1, 'tula', 1),
        arm(1, 'mozhaisk'),
        arm(1, 'tula'),
        rec(1, 'shakhovskaya'),
        { ...inf(1, 'moscow', 2), fresh: true },
      ],
      aims: ['volokolamsk', 'mozhaisk', 'maloyaroslavets', 'kaluga', 'tula', 'moscow'],
      turns: 11,
      arrivals: [
        { turn: 2, side: 0, type: 'armour' },
        { turn: 2, side: 0, type: 'infantry' },
        { turn: 3, side: 0, type: 'infantry' },
        { turn: 4, side: 0, type: 'armour' },
        { turn: 4, side: 0, type: 'infantry' },
        { turn: 4, side: 1, type: 'infantry' },
        { turn: 4, side: 1, type: 'infantry' },
        { turn: 6, side: 1, type: 'armour' },
        { turn: 6, side: 1, type: 'infantry' },
      ],
      destroy: [1, 3],
      player: 1,
      enemy: 'maneuver',
    },
    {
      id: 'counterblow@1',
      name: 'Before Moscow',
      date: 'December 1941',
      briefing:
        'The panzers stopped in the snow at the Moscow–Volga canal, on the edge of Krasnaya Polyana ' +
        'and around Tula, at the end of their fuel and with nothing behind them. The Siberian ' +
        'armies are in position. Strike both spearheads at once — Kalinin, Klin and Solnechnogorsk in ' +
        'the north, Venyov and Kaluga in the south — and drive them back from the capital. Hold Tula, ' +
        'and hold more of the eight objectives than they do when the offensive ends.',
      mapId: 'moscow',
      sides: ['Germany', 'Soviet Union'],
      held: [
        'rzhev', 'staritsa', 'zubtsov', 'sychevka', 'vyazma', 'gzhatsk', 'kalinin', 'lotoshino', 'zavidovo',
        'shakhovskaya', 'volokolamsk', 'klin', 'solnechnogorsk', 'istra', 'krasnayapolyana', 'yakhroma', 'ruza',
        'mozhaisk', 'vereya', 'borovsk', 'narofominsk', 'medyn', 'maloyaroslavets', 'kondrovo', 'yukhnov', 'kaluga',
        'mosalsk', 'kirov', 'sukhinichi', 'kozelsk', 'likhvin', 'odoyev', 'belev', 'bolkhov', 'orel', 'mtsensk',
        'chern', 'plavsk', 'shchekino', 'bogoroditsk', 'stalinogorsk', 'venyov', 'mikhaylov', 'yefremov',
      ],
      home: [['vyazma', 'rzhev', 'orel', 'sychevka'], ['moscow', 'zagorsk', 'noginsk', 'kolomna', 'ryazan']],
      formations: [
        inf(0, 'kalinin'),
        inf(0, 'kalinin'),
        { side: 0, type: 'armour', at: 'klin', strength: 2 },
        inf(0, 'klin', 2),
        { side: 0, type: 'armour', at: 'solnechnogorsk', strength: 2 },
        inf(0, 'solnechnogorsk', 2),
        { side: 0, type: 'armour', at: 'krasnayapolyana', strength: 2 },
        inf(0, 'krasnayapolyana', 2),
        { side: 0, type: 'armour', at: 'yakhroma', strength: 2 },
        inf(0, 'istra', 2),
        inf(0, 'istra', 2),
        inf(0, 'volokolamsk'),
        inf(0, 'ruza'),
        inf(0, 'narofominsk'),
        inf(0, 'maloyaroslavets'),
        inf(0, 'kaluga'),
        inf(0, 'kaluga'),
        { side: 0, type: 'armour', at: 'venyov', strength: 2 },
        inf(0, 'venyov', 2),
        { side: 0, type: 'armour', at: 'stalinogorsk', strength: 2 },
        inf(0, 'mikhaylov', 2),
        inf(0, 'shchekino', 2),
        inf(0, 'odoyev'),

        inf(1, 'konakovo', 2),
        inf(1, 'dmitrov', 2),
        inf(1, 'moscow', 2),
        inf(1, 'zvenigorod', 2),
        inf(1, 'kubinka', 2),
        inf(1, 'serpukhov', 2),
        inf(1, 'tula', 2),
        inf(1, 'kashira', 2),
        arm(1, 'moscow'),
        arm(1, 'tula'),
        rec(1, 'tarusa'),
        { ...inf(1, 'dmitrov'), fresh: true },
        { ...inf(1, 'kimry'), fresh: true },
        { ...inf(1, 'ryazan'), fresh: true },
        { ...inf(1, 'podolsk'), fresh: true },
        { ...arm(1, 'kashira'), fresh: true },
        { ...arm(1, 'zagorsk'), fresh: true },
      ],
      aims: ['kalinin', 'klin', 'solnechnogorsk', 'istra', 'volokolamsk', 'venyov', 'kaluga', 'tula'],
      turns: 9,
      arrivals: [
        { turn: 3, side: 0, type: 'infantry' },
        { turn: 5, side: 0, type: 'infantry' },
        { turn: 2, side: 1, type: 'infantry' },
        { turn: 3, side: 1, type: 'armour' },
        { turn: 4, side: 1, type: 'infantry' },
      ],
      player: 1,
      enemy: 'depth',
    },
  ],
}
