import boardData from '../../data/board.json'
import geoData from '../../data/territories.json'
import seaData from '../../data/sea-routes.json'

export type TerritoryId = string
export type ContinentId = keyof typeof boardData.continents

export interface TerritoryGeometry {
  id: TerritoryId
  continent: ContinentId
  /** label anchor, in map units */
  cx: number
  cy: number
  /** SVG path data */
  d: string
}

export const GEOMETRY = geoData.territories as TerritoryGeometry[]
export const TERRITORY_IDS: TerritoryId[] = GEOMETRY.map((t) => t.id)
export const ADJACENCY = boardData.adjacency as Record<TerritoryId, TerritoryId[]>
export const TERRITORY_NAMES = boardData.names as Record<TerritoryId, string>
export const CONTINENTS = boardData.continents as Record<ContinentId, { name: string; bonus: number }>
export const CONTINENT_IDS = Object.keys(CONTINENTS) as ContinentId[]

export const CONTINENT_OF: Record<TerritoryId, ContinentId> = Object.fromEntries(
  GEOMETRY.map((t) => [t.id, t.continent]),
)

export const TERRITORIES_IN: Record<ContinentId, TerritoryId[]> = Object.fromEntries(
  CONTINENT_IDS.map((c) => [c, GEOMETRY.filter((t) => t.continent === c).map((t) => t.id)]),
) as Record<ContinentId, TerritoryId[]>

/** Extra room below the map so the floating action dock never covers Argentina. */
export const VIEW_BOX = '10 4 735 548'

/**
 * Adjacent territories that don't share a land border, with the nearest point on
 * each coastline. Generated by scripts/solve-sea-routes.mjs.
 */
export interface SeaRoute {
  a: TerritoryId
  b: TerritoryId
  pa: [number, number]
  pb: [number, number]
  dist: number
}
export const SEA_ROUTES = seaData.routes as SeaRoute[]

/**
 * Alaska <-> Kamchatka spans the whole map, so instead of one absurd arc it draws
 * as a stub running off each edge of the world.
 */
export interface WrapStub {
  territory: TerritoryId
  from: [number, number]
  toX: number
}
export const WRAP_STUBS = seaData.wrap as WrapStub[]

/** Quick lookup: is this pair a water crossing rather than a land border? */
const SEA_KEYS = new Set([
  ...SEA_ROUTES.map((r) => [r.a, r.b].sort().join('|')),
  WRAP_STUBS.length === 2 ? [WRAP_STUBS[0].territory, WRAP_STUBS[1].territory].sort().join('|') : '',
])
export const isSeaCrossing = (a: TerritoryId, b: TerritoryId) => SEA_KEYS.has([a, b].sort().join('|'))

/** Open-ocean anchors for continent labels — see scripts/solve-label-anchors.mjs */
/**
 * All six sit in open water — the box each label occupies is clear of land by at
 * least 8 map units. Generated by scripts/solve-label-anchors.mjs.
 */
export const CONTINENT_LABEL_POS: Record<ContinentId, [number, number]> = {
  northAmerica: [113, 32],
  europe: [338, 67],
  asia: [606, 18],
  southAmerica: [114, 377],
  africa: [344, 404],
  australia: [572, 422],
}
